/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mpc_cggmp_util_MetalBigIntegerBackend */

#ifndef _Included_com_example_mpc_cggmp_util_MetalBigIntegerBackend
#define _Included_com_example_mpc_cggmp_util_MetalBigIntegerBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeInitWithShaderPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeInitWithShaderPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeIsAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeIsAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeGetDeviceName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeGetDeviceName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeModPow
 * Signature: (J[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeModPow
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeModPowDirect
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeModPowDirect
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jintArray, jintArray, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeBatchModPow
 * Signature: (J[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeBatchModPow
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeBatchModPowDirect
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeBatchModPowDirect
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jintArray, jintArray, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeComputeAffGProofTuple
 * Signature: (J[I[I[I[I[I[I[I[I[I[I[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeComputeAffGProofTuple
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeComputeAffGProofTupleDirect
 * Signature: (J[I[I[I[I[I[I[I[I[I[Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeComputeAffGProofTupleDirect
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeComputeDecProofTuple
 * Signature: (J[I[I[I[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeComputeDecProofTuple
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeComputeDecProofTupleDirect
 * Signature: (J[I[I[I[I[I[Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeComputeDecProofTupleDirect
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeModInverse
 * Signature: (J[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeModInverse
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeModInverseDirect
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeModInverseDirect
  (JNIEnv *, jobject, jlong, jobject, jobject, jintArray, jintArray, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeMultiply
 * Signature: (J[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeMultiply
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeMultiplyDirect
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeMultiplyDirect
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeBatchModPowDifferentExp
 * Signature: (J[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeBatchModPowDifferentExp
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackend
 * Method:    nativeBatchModPowDifferentExpDirect
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackend_nativeBatchModPowDifferentExpDirect
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jintArray, jintArray, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
