{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0.jar",
          "url": "spring-boot-starter-logging-3.0.0.jar",
          "size": 4756,
          "sha512": "e06ec546ecbd804fa2cdf00f097b11c6697b7e3326ac7e6d481009e16120738ab249a19758961608a91f2b65075c6bbd308890aed5daff2fed29067672bc209e",
          "sha256": "befcac9c8f2517280aaf91a1bc9bade2b8af4e82834de92ef4d1f5c1a3017ada",
          "sha1": "af37a21b0be9c0c8cd11e3f8a3330b314af639d3",
          "md5": "b719004b4ca6887df22f0f56be066c25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0.jar",
          "url": "spring-boot-starter-logging-3.0.0.jar",
          "size": 4756,
          "sha512": "e06ec546ecbd804fa2cdf00f097b11c6697b7e3326ac7e6d481009e16120738ab249a19758961608a91f2b65075c6bbd308890aed5daff2fed29067672bc209e",
          "sha256": "befcac9c8f2517280aaf91a1bc9bade2b8af4e82834de92ef4d1f5c1a3017ada",
          "sha1": "af37a21b0be9c0c8cd11e3f8a3330b314af639d3",
          "md5": "b719004b4ca6887df22f0f56be066c25"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0.jar",
          "url": "spring-boot-starter-logging-3.0.0.jar",
          "size": 4756,
          "sha512": "e06ec546ecbd804fa2cdf00f097b11c6697b7e3326ac7e6d481009e16120738ab249a19758961608a91f2b65075c6bbd308890aed5daff2fed29067672bc209e",
          "sha256": "befcac9c8f2517280aaf91a1bc9bade2b8af4e82834de92ef4d1f5c1a3017ada",
          "sha1": "af37a21b0be9c0c8cd11e3f8a3330b314af639d3",
          "md5": "b719004b4ca6887df22f0f56be066c25"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0.jar",
          "url": "spring-boot-starter-logging-3.0.0.jar",
          "size": 4756,
          "sha512": "e06ec546ecbd804fa2cdf00f097b11c6697b7e3326ac7e6d481009e16120738ab249a19758961608a91f2b65075c6bbd308890aed5daff2fed29067672bc209e",
          "sha256": "befcac9c8f2517280aaf91a1bc9bade2b8af4e82834de92ef4d1f5c1a3017ada",
          "sha1": "af37a21b0be9c0c8cd11e3f8a3330b314af639d3",
          "md5": "b719004b4ca6887df22f0f56be066c25"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0-javadoc.jar",
          "url": "spring-boot-starter-logging-3.0.0-javadoc.jar",
          "size": 4742,
          "sha512": "f3b30fae66a0ce19c8d8efda22332fc274832bac2b963114f322c63aaf9cdcfff17c4e4bf29892a883f50a52510c770047d7a84832e59f2fd7c7fb64a4a05041",
          "sha256": "373703a35e6e2d34526c87df1ff9241413f42dc60d56b19349cbef7cbecc8473",
          "sha1": "0c2ed2f03253186edbe3b88a1a8caae1c1fda545",
          "md5": "d187dc0acbbb2b9a954296a30d4aa07e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.0.0-sources.jar",
          "url": "spring-boot-starter-logging-3.0.0-sources.jar",
          "size": 4741,
          "sha512": "8148661e1a727168503cce8d7dc7f3fc606bad551dd639da23449ed1bc041bed94cabee75c4bc112cf0718aff1a5394ce938641157f305ee4cd6eee5098dd9cb",
          "sha256": "b8d286ab2de4aa2c5fb96a0c7bcf155bc338952a34f234e828419941af9f27c8",
          "sha1": "3508cf04b732878da642fb5d2eb4a9aa2a2e6bbd",
          "md5": "2d24dd64016d79a1986dcf598236687e"
        }
      ]
    }
  ]
}
