{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0.jar",
          "url": "spring-boot-autoconfigure-3.0.0.jar",
          "size": 1623827,
          "sha512": "329a476ddec93354e01efac4833412c18c60848aca06123d1b11cebfa8b7f475275800bd200eed0d954cc4a82edf29bacf0a1313c8c68398e065753df280db68",
          "sha256": "fc2f6d4cb382add6f851cd4ac0c682c634c109d1bb83601756236ab8e1d1ddda",
          "sha1": "11c57cfd7a6c6ef2cf16cc91c4d9173f6ab16dd2",
          "md5": "555fc654bf8085010b1abcfc92d8f4a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0.jar",
          "url": "spring-boot-autoconfigure-3.0.0.jar",
          "size": 1623827,
          "sha512": "329a476ddec93354e01efac4833412c18c60848aca06123d1b11cebfa8b7f475275800bd200eed0d954cc4a82edf29bacf0a1313c8c68398e065753df280db68",
          "sha256": "fc2f6d4cb382add6f851cd4ac0c682c634c109d1bb83601756236ab8e1d1ddda",
          "sha1": "11c57cfd7a6c6ef2cf16cc91c4d9173f6ab16dd2",
          "md5": "555fc654bf8085010b1abcfc92d8f4a9"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0.jar",
          "url": "spring-boot-autoconfigure-3.0.0.jar",
          "size": 1623827,
          "sha512": "329a476ddec93354e01efac4833412c18c60848aca06123d1b11cebfa8b7f475275800bd200eed0d954cc4a82edf29bacf0a1313c8c68398e065753df280db68",
          "sha256": "fc2f6d4cb382add6f851cd4ac0c682c634c109d1bb83601756236ab8e1d1ddda",
          "sha1": "11c57cfd7a6c6ef2cf16cc91c4d9173f6ab16dd2",
          "md5": "555fc654bf8085010b1abcfc92d8f4a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0.jar",
          "url": "spring-boot-autoconfigure-3.0.0.jar",
          "size": 1623827,
          "sha512": "329a476ddec93354e01efac4833412c18c60848aca06123d1b11cebfa8b7f475275800bd200eed0d954cc4a82edf29bacf0a1313c8c68398e065753df280db68",
          "sha256": "fc2f6d4cb382add6f851cd4ac0c682c634c109d1bb83601756236ab8e1d1ddda",
          "sha1": "11c57cfd7a6c6ef2cf16cc91c4d9173f6ab16dd2",
          "md5": "555fc654bf8085010b1abcfc92d8f4a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.0.0-javadoc.jar",
          "size": 2612875,
          "sha512": "f455fdcced4a5f72a89268245fd0c9a3fcd4e3a9178f0ac386e365c76d6d656d359c81a45424e32ca29b5e6f63a65f6bb1209f86b97b3f0c262e8e827c369270",
          "sha256": "637124fe9dfcc8fbdc6f545dfb37112c1d3aeba9debc2d0b5c725b1fac741989",
          "sha1": "964e28bfdb8ee9e312e92ec7618b69d393f67204",
          "md5": "b4b068fcf6fdc2a8a61441581abea976"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.0-sources.jar",
          "url": "spring-boot-autoconfigure-3.0.0-sources.jar",
          "size": 961553,
          "sha512": "c0d07fe99f0d580e0645d7bd012635a67e07890358cc1367cfae7fc75a2580e2a5c4e6024d501168c7aa5159d54ada69ac1014539d71d63f3b8c5ef2b299d462",
          "sha256": "bad38573f4b8564b625fec7d37e9dde48e6edc28fda1807f973a0f070f35c308",
          "sha1": "a12cb1f4a81c222b69839da81b3a024607f27555",
          "md5": "b713b6b1a61f729bac3b8a38dbf1346c"
        }
      ]
    }
  ]
}
