{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0.jar",
          "url": "spring-boot-starter-json-3.0.0.jar",
          "size": 4746,
          "sha512": "201067644312e5f07af53b2e512b6578552293365533abd9833dae2bd686c5ab9a62268adc55f0efd627986c15d4884561d7813733f181af146b8bce6984b988",
          "sha256": "ca890f3a719a5ce66751ec0c204196bf1998e235c279e82209ef738d2d830107",
          "sha1": "beb1a175ad3cdec82ebd36dd1ddd08a9738a2d86",
          "md5": "708e1073410d23c9993e60bc8f701e31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0.jar",
          "url": "spring-boot-starter-json-3.0.0.jar",
          "size": 4746,
          "sha512": "201067644312e5f07af53b2e512b6578552293365533abd9833dae2bd686c5ab9a62268adc55f0efd627986c15d4884561d7813733f181af146b8bce6984b988",
          "sha256": "ca890f3a719a5ce66751ec0c204196bf1998e235c279e82209ef738d2d830107",
          "sha1": "beb1a175ad3cdec82ebd36dd1ddd08a9738a2d86",
          "md5": "708e1073410d23c9993e60bc8f701e31"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0.jar",
          "url": "spring-boot-starter-json-3.0.0.jar",
          "size": 4746,
          "sha512": "201067644312e5f07af53b2e512b6578552293365533abd9833dae2bd686c5ab9a62268adc55f0efd627986c15d4884561d7813733f181af146b8bce6984b988",
          "sha256": "ca890f3a719a5ce66751ec0c204196bf1998e235c279e82209ef738d2d830107",
          "sha1": "beb1a175ad3cdec82ebd36dd1ddd08a9738a2d86",
          "md5": "708e1073410d23c9993e60bc8f701e31"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0.jar",
          "url": "spring-boot-starter-json-3.0.0.jar",
          "size": 4746,
          "sha512": "201067644312e5f07af53b2e512b6578552293365533abd9833dae2bd686c5ab9a62268adc55f0efd627986c15d4884561d7813733f181af146b8bce6984b988",
          "sha256": "ca890f3a719a5ce66751ec0c204196bf1998e235c279e82209ef738d2d830107",
          "sha1": "beb1a175ad3cdec82ebd36dd1ddd08a9738a2d86",
          "md5": "708e1073410d23c9993e60bc8f701e31"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0-javadoc.jar",
          "url": "spring-boot-starter-json-3.0.0-javadoc.jar",
          "size": 4741,
          "sha512": "08805cd792e2e5fbc65aecea65f4975f622ddb5133eaee91925d06db7e0215258cf5de48a63c83a84dbcf18ee5eadc47bc4b29390f82074cde4f56a058cc2c39",
          "sha256": "6c991f2c65e00960915ce064cf940a0f6d5024facc8e6ffabd7d8264cdf29403",
          "sha1": "2f42bb2880fd837ad60b676891d2f81ac8ab25c4",
          "md5": "4bc8433c7aca1fea951c987d17c67826"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.0-sources.jar",
          "url": "spring-boot-starter-json-3.0.0-sources.jar",
          "size": 4739,
          "sha512": "a4363caa8d94737410cac7b3bc8a6137c53af66738541294a45a1fc9879d4823443e8477516abaf01f03df26ac8a0fe939fc3facccef2be341ca2e41795c86e0",
          "sha256": "9ab9fdd84296731e3df9a1aca5dab684407a2951b61f3d72a1332845346485ab",
          "sha1": "1659f9bc1600ce6f6efcba92e12fbcd45abebe49",
          "md5": "28cc33ffd28d48b54bc00fded7186a24"
        }
      ]
    }
  ]
}
