plugins {
    id 'java'
    id 'idea'
    id 'org.springframework.boot' version '3.0.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'pmd'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

// 配置 IDEA 输出目录
idea {
    module {
        outputDir = file('build/classes/java/main')
        testOutputDir = file('build/classes/java/test')
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.xerial:sqlite-jdbc:3.40.1.0'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.77'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.77'
    implementation 'org.bouncycastle:bcutil-jdk18on:1.77'
    implementation 'com.google.guava:guava:32.0.0-jre'
    implementation 'io.netty:netty-all:4.1.97.Final'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

pmd {
    toolVersion = '6.55.0'
    rulesMinimumPriority = 5
    ruleSets = []
    ruleSetFiles = files('config/pmd/ruleset.xml')
}

// 为每个节点创建构建任务
for (int i = 1; i <= 5; i++) {
    task "bootRunNode${i}"(type: org.springframework.boot.gradle.tasks.run.BootRun) {
        group = 'application'
        description = "Run node ${i}"
        args = ["--spring.profiles.active=node${i}"]
        classpath = sourceSets.main.runtimeClasspath
        mainClass = 'com.example.mpc.MpcApplication'
    }
}
