{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0.jar",
          "url": "spring-boot-loader-tools-3.0.0.jar",
          "size": 247483,
          "sha512": "518dea1829939519db7929fd9096859deb46316307c1c18377de7517eb99041ad82a37e5dd3ec2af75559420f43c920ded292c087e275c968813e8af08113070",
          "sha256": "f4f0d9332672c02d05186c73d38eab5f1a56cc560525cf4e4b8884806c8c1294",
          "sha1": "e79983673704da92295ae90784bfabb5b5231d14",
          "md5": "20486d969700f097b5fd098f577f77fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0.jar",
          "url": "spring-boot-loader-tools-3.0.0.jar",
          "size": 247483,
          "sha512": "518dea1829939519db7929fd9096859deb46316307c1c18377de7517eb99041ad82a37e5dd3ec2af75559420f43c920ded292c087e275c968813e8af08113070",
          "sha256": "f4f0d9332672c02d05186c73d38eab5f1a56cc560525cf4e4b8884806c8c1294",
          "sha1": "e79983673704da92295ae90784bfabb5b5231d14",
          "md5": "20486d969700f097b5fd098f577f77fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0-javadoc.jar",
          "url": "spring-boot-loader-tools-3.0.0-javadoc.jar",
          "size": 237022,
          "sha512": "7e18d49fdd4296bbdbe55d9aa5e5d46218d6a7213b7a7794e8b9d1db89ddbd5f478d26acf80035418dad6f2b8e146a27f0306ad4babb61f8d303bf807a2c6608",
          "sha256": "225341011b89e11ce8b2a12a0e37fa741fb74f2a9649b8d4fc06afa607e8e4e4",
          "sha1": "ce291dcd867c0b639b0ba074eeef9bfcdc59d043",
          "md5": "dba78d5766236966053454711bf0b04b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0-sources.jar",
          "url": "spring-boot-loader-tools-3.0.0-sources.jar",
          "size": 69969,
          "sha512": "8fce8d9eed908c263cb5f437b2dd9fe80eb2c34c44180735dfbbc5cb309976deb17229db985e4a6ee477a5c263d3d498fda684b5d62e8c667a0bdafd7b1812f1",
          "sha256": "529d542f8a39bbccfda5b4945cea271e551896384ce51a1f8e75c6ebf6fa8994",
          "sha1": "10c2d2e2cb5cc240c07189b8cda3bef6748869dc",
          "md5": "4d702fad45af947c4a4d606f70acd658"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0.jar",
          "url": "spring-boot-loader-tools-3.0.0.jar",
          "size": 247483,
          "sha512": "518dea1829939519db7929fd9096859deb46316307c1c18377de7517eb99041ad82a37e5dd3ec2af75559420f43c920ded292c087e275c968813e8af08113070",
          "sha256": "f4f0d9332672c02d05186c73d38eab5f1a56cc560525cf4e4b8884806c8c1294",
          "sha1": "e79983673704da92295ae90784bfabb5b5231d14",
          "md5": "20486d969700f097b5fd098f577f77fa"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.0.jar",
          "url": "spring-boot-loader-tools-3.0.0.jar",
          "size": 247483,
          "sha512": "518dea1829939519db7929fd9096859deb46316307c1c18377de7517eb99041ad82a37e5dd3ec2af75559420f43c920ded292c087e275c968813e8af08113070",
          "sha256": "f4f0d9332672c02d05186c73d38eab5f1a56cc560525cf4e4b8884806c8c1294",
          "sha1": "e79983673704da92295ae90784bfabb5b5231d14",
          "md5": "20486d969700f097b5fd098f577f77fa"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.0"
        }
      ]
    }
  ]
}
