{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.0.2.jar",
          "url": "spring-web-6.0.2.jar",
          "size": 1733009,
          "sha512": "ca6d57edcd255083579e97238d1425657eb481d8c7c4ad8e6c9ec5109bd09278853243590f7988eaa3f033e5e7c8e6323189c091a293c1137db600be75e01cc6",
          "sha256": "b5b0b095e64df11df611ce1fe143883a0a2f58be43f1766d12acce1f06dee714",
          "sha1": "39dde8bfcc9074af0fcec924ca7465cb90eb25d4",
          "md5": "48429b4563f669be0a7f15f22ca6a1c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.0.2.jar",
          "url": "spring-web-6.0.2.jar",
          "size": 1733009,
          "sha512": "ca6d57edcd255083579e97238d1425657eb481d8c7c4ad8e6c9ec5109bd09278853243590f7988eaa3f033e5e7c8e6323189c091a293c1137db600be75e01cc6",
          "sha256": "b5b0b095e64df11df611ce1fe143883a0a2f58be43f1766d12acce1f06dee714",
          "sha1": "39dde8bfcc9074af0fcec924ca7465cb90eb25d4",
          "md5": "48429b4563f669be0a7f15f22ca6a1c7"
        }
      ]
    }
  ]
}
