{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.14.1.jar",
          "url": "jackson-datatype-jsr310-2.14.1.jar",
          "size": 120588,
          "sha512": "5e42873b9b195fb9afb0a3c9dd88fa2346830f10f52e367ee7d88329c5bbbca974ef0417048c5ea000fbab3493dd399c834328f381c2aa045f51c0e54ba90f96",
          "sha256": "d735a51619e918103594d19308cc5e3ce9c6aeb7709c1a92c1b5fcd14eca9925",
          "sha1": "6c2c021e820f806087e33caa84178e478566a9b0",
          "md5": "61786e0be7198f3394f25938cfc7350c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.14.1.jar",
          "url": "jackson-datatype-jsr310-2.14.1.jar",
          "size": 120588,
          "sha512": "5e42873b9b195fb9afb0a3c9dd88fa2346830f10f52e367ee7d88329c5bbbca974ef0417048c5ea000fbab3493dd399c834328f381c2aa045f51c0e54ba90f96",
          "sha256": "d735a51619e918103594d19308cc5e3ce9c6aeb7709c1a92c1b5fcd14eca9925",
          "sha1": "6c2c021e820f806087e33caa84178e478566a9b0",
          "md5": "61786e0be7198f3394f25938cfc7350c"
        }
      ]
    }
  ]
}
