package com.example.mpc.enums;

public enum MessageType {
    GENNARO_DKG_INIT,
    GENNARO_COMMITMENT,
    GENNARO_SHARE,
    GENNARO_PUBLIC_KEY_PART,
    CGGMP_DKG_INIT,
    CGGMP_DKG_ROUND1,
    CGGMP_DKG_ROUND2,
    CGGMP_DKG_MTA_INIT,
    CGGMP_DKG_MTA_RESPONSE,
    CGGMP_DKG_MTA_ALPHA,
    GG20_SIGN_INIT,
    CGGMP_SIGN_GAMMA,
    CGGMP_SIGN_MTA_KA_INIT,
    CGGMP_SIGN_MTA_KA_RESPONSE,
    CGGMP_SIGN_U_COMMIT,
    CGGMP_SIGN_U_SHARE,
    CGGMP_SIGN_U_OPEN,
    CGGMP_SIGN_MTA_ST_INIT,
    CGGMP_SIGN_MTA_ST_RESPONSE,
    CGGMP_SIGN_S_SHARE
}
