package com.example.mpc.enums;

public enum MessageType {
    COMMITMENT,
    SHARE,
    PUBLIC_KEY_PART,
    SIGNATURE_SHARE,
    SIGN_COMMITMENT,
    DKG_INIT,
    SIGN_INIT,
    PING,
    PONG,
    CGGMP_DKG_INIT,
    CGGMP_DKG_ROUND1,
    CGGMP_DKG_ROUND2,
    CGGMP_SIGN_INIT,
    CGGMP_SIGN_ROUND1,
    CGGMP_SIGN_ROUND2,
    CGGMP_SIGN_ROUND3,
    GG20_SIGN_INIT,
    GG20_GAMMA_COMMITMENT,
    GG20_MTA_INIT,
    GG20_MTA_RESPONSE,
    GG20_OFFLINE,
    GG20_PARTIAL_S
}
