{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.0.2.jar",
          "url": "spring-webmvc-6.0.2.jar",
          "size": 1006689,
          "sha512": "0a8760c78ae016c2c3ed104ff12cb9d9f27981c587b76e9607d76df1e0dba389c63091e3426ce96dcbfb359c30c0621c5ec877cde209941da69890c3491efed1",
          "sha256": "de7f62edcae549d335e860956b6def17adf34738b6e93e5529ed3dae2fbc9951",
          "sha1": "cf96960288ba6a95da3488b6d255803c50fa1927",
          "md5": "839db90d5e34f20603a29440e702e3ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.0.2.jar",
          "url": "spring-webmvc-6.0.2.jar",
          "size": 1006689,
          "sha512": "0a8760c78ae016c2c3ed104ff12cb9d9f27981c587b76e9607d76df1e0dba389c63091e3426ce96dcbfb359c30c0621c5ec877cde209941da69890c3491efed1",
          "sha256": "de7f62edcae549d335e860956b6def17adf34738b6e93e5529ed3dae2fbc9951",
          "sha1": "cf96960288ba6a95da3488b6d255803c50fa1927",
          "md5": "839db90d5e34f20603a29440e702e3ea"
        }
      ]
    }
  ]
}
