/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp */

#ifndef _Included_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
#define _Included_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeInitWithShaderPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeInitWithShaderPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeIsAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeIsAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeModPow
 * Signature: (J[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeModPow
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeComputeAffGProofTuple
 * Signature: (J[I[I[I[I[I[I[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeComputeAffGProofTuple
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeComputeDecProofTuple
 * Signature: (J[I[I[I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeComputeDecProofTuple
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeModInverse
 * Signature: (J[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeModInverse
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeMultiply
 * Signature: (J[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeMultiply
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp
 * Method:    nativeBatchModPowDifferentExp
 * Signature: (J[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_mpc_cggmp_util_MetalBigIntegerBackendTemp_nativeBatchModPowDifferentExp
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
