{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.0.2.jar",
          "url": "spring-aop-6.0.2.jar",
          "size": 395698,
          "sha512": "2ccfc51e666f0224db83b872804d9e7e7330cd984cf815b85767512255162c5ed89d01948153cc82ec1c22b6e4522008d2503cbd8a905881b9c22352fe599210",
          "sha256": "d0672f280835bda5abe463d37e5aa0cd66d89c230467e266c444914d15c35c65",
          "sha1": "fe73295dd65e6b2f53986622c1e622cd3d09aa03",
          "md5": "baae6deb6d5d97006cabb67ccc875fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.0.2.jar",
          "url": "spring-aop-6.0.2.jar",
          "size": 395698,
          "sha512": "2ccfc51e666f0224db83b872804d9e7e7330cd984cf815b85767512255162c5ed89d01948153cc82ec1c22b6e4522008d2503cbd8a905881b9c22352fe599210",
          "sha256": "d0672f280835bda5abe463d37e5aa0cd66d89c230467e266c444914d15c35c65",
          "sha1": "fe73295dd65e6b2f53986622c1e622cd3d09aa03",
          "md5": "baae6deb6d5d97006cabb67ccc875fa5"
        }
      ]
    }
  ]
}
