{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.0.0.jar",
          "url": "spring-boot-starter-3.0.0.jar",
          "size": 4767,
          "sha512": "45348d666fb76086ba528af3314108f0c4e32c36f67b575240fdefe0e0e241b53ccdaec0e1e94257ec5ebbac175da5d4ce4c013620e9cb20cb94b25ed02918c1",
          "sha256": "980298cf86b75945f81474065c9ba90c765473e1e7504d42c5dcd5c42754b644",
          "sha1": "18c02ab19529d866723b40c03021cd731c3edb50",
          "md5": "a5ec39ff239ebf3adf8d926bcaaae89b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.0.0.jar",
          "url": "spring-boot-starter-3.0.0.jar",
          "size": 4767,
          "sha512": "45348d666fb76086ba528af3314108f0c4e32c36f67b575240fdefe0e0e241b53ccdaec0e1e94257ec5ebbac175da5d4ce4c013620e9cb20cb94b25ed02918c1",
          "sha256": "980298cf86b75945f81474065c9ba90c765473e1e7504d42c5dcd5c42754b644",
          "sha1": "18c02ab19529d866723b40c03021cd731c3edb50",
          "md5": "a5ec39ff239ebf3adf8d926bcaaae89b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.0.jar",
          "url": "spring-boot-starter-3.0.0.jar",
          "size": 4767,
          "sha512": "45348d666fb76086ba528af3314108f0c4e32c36f67b575240fdefe0e0e241b53ccdaec0e1e94257ec5ebbac175da5d4ce4c013620e9cb20cb94b25ed02918c1",
          "sha256": "980298cf86b75945f81474065c9ba90c765473e1e7504d42c5dcd5c42754b644",
          "sha1": "18c02ab19529d866723b40c03021cd731c3edb50",
          "md5": "a5ec39ff239ebf3adf8d926bcaaae89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.0.jar",
          "url": "spring-boot-starter-3.0.0.jar",
          "size": 4767,
          "sha512": "45348d666fb76086ba528af3314108f0c4e32c36f67b575240fdefe0e0e241b53ccdaec0e1e94257ec5ebbac175da5d4ce4c013620e9cb20cb94b25ed02918c1",
          "sha256": "980298cf86b75945f81474065c9ba90c765473e1e7504d42c5dcd5c42754b644",
          "sha1": "18c02ab19529d866723b40c03021cd731c3edb50",
          "md5": "a5ec39ff239ebf3adf8d926bcaaae89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.0-javadoc.jar",
          "url": "spring-boot-starter-3.0.0-javadoc.jar",
          "size": 4733,
          "sha512": "e6f50ee89c6395b92ce86430c5a02f9161c39900bdec72cc7f731eba4e495c93fed7140d2e42acbbca0059c14bc0af258fd7e2bd9f6e9bfcc5fcbdb263b53161",
          "sha256": "851714a0250c53a27b302c1404120fc0d8ff77bcc2544b3b29293ead8634b9b1",
          "sha1": "3298650e89ca7c3f27def5333028473243a84020",
          "md5": "12e399667c229db35f8ba47b93d6c81d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.0-sources.jar",
          "url": "spring-boot-starter-3.0.0-sources.jar",
          "size": 4732,
          "sha512": "68391b026e99a3313507df192eed6fe6f0a46fb898244ed0577e758178e2cd25f2ba01f3ca260faf4e784c62d641f23d482209656827c915dc42f7cc5c631c05",
          "sha256": "78595d7d65a0edd847175c6faec6f816b23fd4e2f30b86501ee5050707a05d00",
          "sha1": "4b7419066bb731fd44cfe08ef4fae70194f21f80",
          "md5": "f799b8761ff87839cd94b0ef090f2d1a"
        }
      ]
    }
  ]
}
