{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.0.2.jar",
          "url": "spring-expression-6.0.2.jar",
          "size": 291111,
          "sha512": "0d2a62dcccb4db38a1e45e744d392cfb53a88ea4a6514bcb9c9d8fb4603b224b397fdf140ffd8095892c916d32af9908f870edd107870fbaaa6a87b66adcdcb6",
          "sha256": "76ad63b70277f5f68e6c763ac1c473956c17d3d17ae3d4825d627e96db1a8271",
          "sha1": "89687daffb67231f6be7783775c1f0d46f4541fe",
          "md5": "3ead16660ccb931c24a935cabe7d195c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.0.2.jar",
          "url": "spring-expression-6.0.2.jar",
          "size": 291111,
          "sha512": "0d2a62dcccb4db38a1e45e744d392cfb53a88ea4a6514bcb9c9d8fb4603b224b397fdf140ffd8095892c916d32af9908f870edd107870fbaaa6a87b66adcdcb6",
          "sha256": "76ad63b70277f5f68e6c763ac1c473956c17d3d17ae3d4825d627e96db1a8271",
          "sha1": "89687daffb67231f6be7783775c1f0d46f4541fe",
          "md5": "3ead16660ccb931c24a935cabe7d195c"
        }
      ]
    }
  ]
}
