{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.14.1.jar",
          "url": "jackson-module-parameter-names-2.14.1.jar",
          "size": 8607,
          "sha512": "70e16e439a36d0ee1cdf565a654dce8b5a809539f171ab0d149f7eac9d5df41303d432b816b9333e9c36d6718d509e329ddf4ed5eb96d3f6b6d60d18d055fdde",
          "sha256": "c4f00d16d59dee78b19fec6b8cbbe9402a45e37abc889ac9472249c4283465e5",
          "sha1": "551b7a03cb739293ba74f6c45c929623311e1e5d",
          "md5": "8c8a8a0f76f992272c7a9a07e2711668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.14.1.jar",
          "url": "jackson-module-parameter-names-2.14.1.jar",
          "size": 8607,
          "sha512": "70e16e439a36d0ee1cdf565a654dce8b5a809539f171ab0d149f7eac9d5df41303d432b816b9333e9c36d6718d509e329ddf4ed5eb96d3f6b6d60d18d055fdde",
          "sha256": "c4f00d16d59dee78b19fec6b8cbbe9402a45e37abc889ac9472249c4283465e5",
          "sha1": "551b7a03cb739293ba74f6c45c929623311e1e5d",
          "md5": "8c8a8a0f76f992272c7a9a07e2711668"
        }
      ]
    }
  ]
}
