{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0.jar",
          "url": "spring-boot-starter-web-3.0.0.jar",
          "size": 4802,
          "sha512": "14c39a32e8b0b518ba00e4ebcacebf72ad04563fec5befd945628a806e9703dba379bbf7649c8f5279c937f7ae62d3a2aeedf3da410710ba76d9f773ae021e8a",
          "sha256": "7aa4036278157a3a2ee8bb86aff5017a38b4fd4cddce10de6a44a124a784f9a6",
          "sha1": "5dd6c38f60b915dce2c4a340f4ea68f2e52306f8",
          "md5": "7140ae8611168fa30199b1e352d0979a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0.jar",
          "url": "spring-boot-starter-web-3.0.0.jar",
          "size": 4802,
          "sha512": "14c39a32e8b0b518ba00e4ebcacebf72ad04563fec5befd945628a806e9703dba379bbf7649c8f5279c937f7ae62d3a2aeedf3da410710ba76d9f773ae021e8a",
          "sha256": "7aa4036278157a3a2ee8bb86aff5017a38b4fd4cddce10de6a44a124a784f9a6",
          "sha1": "5dd6c38f60b915dce2c4a340f4ea68f2e52306f8",
          "md5": "7140ae8611168fa30199b1e352d0979a"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0.jar",
          "url": "spring-boot-starter-web-3.0.0.jar",
          "size": 4802,
          "sha512": "14c39a32e8b0b518ba00e4ebcacebf72ad04563fec5befd945628a806e9703dba379bbf7649c8f5279c937f7ae62d3a2aeedf3da410710ba76d9f773ae021e8a",
          "sha256": "7aa4036278157a3a2ee8bb86aff5017a38b4fd4cddce10de6a44a124a784f9a6",
          "sha1": "5dd6c38f60b915dce2c4a340f4ea68f2e52306f8",
          "md5": "7140ae8611168fa30199b1e352d0979a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0.jar",
          "url": "spring-boot-starter-web-3.0.0.jar",
          "size": 4802,
          "sha512": "14c39a32e8b0b518ba00e4ebcacebf72ad04563fec5befd945628a806e9703dba379bbf7649c8f5279c937f7ae62d3a2aeedf3da410710ba76d9f773ae021e8a",
          "sha256": "7aa4036278157a3a2ee8bb86aff5017a38b4fd4cddce10de6a44a124a784f9a6",
          "sha1": "5dd6c38f60b915dce2c4a340f4ea68f2e52306f8",
          "md5": "7140ae8611168fa30199b1e352d0979a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0-javadoc.jar",
          "url": "spring-boot-starter-web-3.0.0-javadoc.jar",
          "size": 4740,
          "sha512": "81bf43a49ef7be9f8dbd58b48ae67047ad899db6cbf22b8e1598557c50b2f405560480d61d229eee5fb9e0058df5e9132fed85e73dd000596ffc75bb34534c07",
          "sha256": "97400c8b712ab5a302a993f162c4fecb6e8e852a30066fa78ecaff4abc18d697",
          "sha1": "29ba3a6987693c74ec2e11062efc946b25315a32",
          "md5": "9f1b14bfab3fbe47848a97b3e30c991e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.0-sources.jar",
          "url": "spring-boot-starter-web-3.0.0-sources.jar",
          "size": 4740,
          "sha512": "7616a7ef2fb2f37fb1b23d539ce76675f42094ddf000992c57d7d92cb5c3b9af66f19f02a7e712259d83bf9909cff996ec5116050aa6b3debd757d3fa0ce3ebc",
          "sha256": "edb368ee77285e8e24c5918564553f3f2fb717b38ffca72d9aeb40c292b27e17",
          "sha1": "e3639c9acf9eece992483b4dd5e8af410d135645",
          "md5": "f41b1224354e5dba7b4eba77e712a771"
        }
      ]
    }
  ]
}
