{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jdk8",
    "version": "2.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.14.1.jar",
          "url": "jackson-datatype-jdk8-2.14.1.jar",
          "size": 34234,
          "sha512": "3623c4eac8c3e57c7917fdb2797811e88e1982ccb0626f19b2990b495ac3285cab6074e99d24b84ab8402b1a98981b1d61a9ead45a3fd226e3f06a290ed870fd",
          "sha256": "6118e1fceab920507f5c0ffd5ec5ccf6d6d645477c47f72592d6eb639ea46fb3",
          "sha1": "eff725a793be3e9a52f0636040dc0b55275f9a74",
          "md5": "4ad4dffc12826cd2fd623863127d42bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.14.1.jar",
          "url": "jackson-datatype-jdk8-2.14.1.jar",
          "size": 34234,
          "sha512": "3623c4eac8c3e57c7917fdb2797811e88e1982ccb0626f19b2990b495ac3285cab6074e99d24b84ab8402b1a98981b1d61a9ead45a3fd226e3f06a290ed870fd",
          "sha256": "6118e1fceab920507f5c0ffd5ec5ccf6d6d645477c47f72592d6eb639ea46fb3",
          "sha1": "eff725a793be3e9a52f0636040dc0b55275f9a74",
          "md5": "4ad4dffc12826cd2fd623863127d42bc"
        }
      ]
    }
  ]
}
